### PR TITLE
Upgrade startscript-parameters to sbt-native-packager-1.0.0

### PR DESCRIPTION
**Pull request by hstraub**
- Add an exception handler in main
- Modify etc-default with JAVA_OPTS parameter

Can you give me a hint, how I can get arguments to the java commandline? I think, I should can pass for example this parameters:

```
mukis-startscript-parameters +Dde.mukis=Tester -interval 20
```

I want to use it in combination with a akka micro kernel package: 
```
-Dconfig.file=$AKKA_HOME/conf/application.conf
```

Thanks!

### CODE REVIEW

**Comment by muuki88** [comment]
> Can you give me a hint, how I can get arguments to the java commandline? I think, I should can pass for example this parameters

The easiest way is to add them in your `build.sbt`

```scala
javaOptions in Universal ++= Seq("mukis-startscript-parameters", "-Dde.mukis=Tester", "-interval", "20")
```

or create `src/universal/conf/application.ini` and use the old `etc-default` style config file.
See [java server customization](http://www.scala-sbt.org/sbt-native-packager/) and [java app customization](http://www.scala-sbt.org/sbt-native-packager/archetypes/java_app/customize.html)

**Comment by muuki88** [comment]
Oh. And the Akka Microkernel package got deprecated. You can achieve the same stuff with `JavaAppPackaging`

**Comment by hstraub** [comment]
Thank you for the quick answer. I will try this!

**Comment by hstraub** [comment]
I updated the startscript-parameters example with both variants. I create a new pull request.

**Pull request closed without merging**
